-- sql to create tables

CREATE TABLE Campaigns (
  ID INTEGER PRIMARY KEY,
  Description varchar(255),
  URL varchar(255),
  Image varchar(255),
  BlockHeightExpiration INTEGER NOT NULL,
  FundingGoal INTEGER NOT NULL,
  TotalRaised INTEGER NOT NULL DEFAULT 0,
  DateCreated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DateUpdated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE Contributions (
  CampaignID INTEGER NOT NULL,
  Principal VARCHAR(255) NOT NULL,
  Amount INTEGER,
  DateCreated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DateUpdated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CampaignID, Principal),
  FOREIGN KEY (CampaignID) REFERENCES Campaigns(ID)
)
