-- sql to create tables

CREATE TABLE Campaigns (
  ID INTEGER PRIMARY KEY,
  Description varchar(255),
  URL varchar(255),
  Image varchar(255),
  DateCreated TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DateUpdated TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE Contributions (
  CampaignID INTEGER NOT NULL,
  Principal VARCHAR(255) NOT NULL,
  Amount INTEGER,
  DateCreated TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DateUpdated TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CampaignID, Principal),
  FOREIGN KEY (CampaignID) REFERENCES Campaigns(ID)
)
